### ISSUE TITLE
Add share possibility to docs site

### ISSUE THREAD

**Issue by lauranovich** [scylladb/sphinx-scylladb-theme#199]
Add a share icon so that users can share the content on their social media or messenger or email platform. 
the icon should be the same universal share icon and should work as it does with all other software websites.

**Comment by tzach** [comment]
Need different design for mobile and desktop

**Comment by dgarcia360** [comment]
I don't think devs will use this feature.

Suppose you are on desktop, and you want to share the link with someone (e.g., Slack). Nowadays, most browsers comes with options to share content to social networks. 

![image](https://user-images.githubusercontent.com/9107969/151121836-38128dc6-6c06-4f34-96c7-f305fff553e1.png)

Additionally, it's normally more convenient to copy and paste the URL rather than give permission to an app to publish a message on my behalf. 


On mobile, most browsers also have this built-in feature to share the page:

![image](https://user-images.githubusercontent.com/9107969/151121364-d4ad1e48-3e83-4f82-a0be-ba71b1d71849.png)

@tzach What do you think? Should we close this issue?
