### ISSUE TITLE
Set correct rel="canonical"  URL

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/sphinx-scylladb-theme#405]
## Context

Feedback:

> It seems all the various docs pages all have the exact same `<link rel="canonical" href="https://docs.scylladb.com/" />`, which hurts SEO. That's probably a pain and not worth the time. The second best solution is to remove that <link rel="canonical" href="https://docs.scylladb.com/" /> altogether.  

## Proposal

To make this tag SEO compliant, we should point to the URL of the latest stable version of the document the user is reading (e.g. https://cloud.docs.scylladb.com/stable/cloud-setup/AWS/index.html).

By doing so, the search engine will prioritize indexing the latest stable version instead of a previous version.

If too complicated, I'll delete the "canonical" tag for now.

**Comment by scynthiadunlop** [comment]
The SEO team is reporting this is still an issue 
![Screen Shot 2022-03-30 at 11 45 35 AM](https://user-images.githubusercontent.com/93212306/160909468-bab94913-fdeb-4fce-ab26-2c514c727178.png)

**Comment by dgarcia360** [comment]
@scynthiadunlop We released the version 1.2.0 of the theme (which includes the fix for this bug), but this was not  installed in scylla-docs project yet.

**Comment by scynthiadunlop** [comment]
@dgarcia360 - Some additional feedback from the SEO team...

The issue is that the good docs URLs instead of all being canonicalized to: https://docs.scylladb.com/ (previous issue) they are now canonicalized to slight variations of themselves.

This is causing the good URLs to be kept out of the index sometimes or at least confusing search crawlers (causing lower keyword rankings for these pages) and now the “/index” versions are being indexed too which causes duplicate content.





Examples:

[https://docs.scylladb.com//architecture/](https://docs.scylladb.com/architecture/) canonicalized to [https://docs.scylladb.com//architecture/index.html](https://docs.scylladb.com/architecture/index.html)

OR

[https://docs.scylladb.com//faq/](https://docs.scylladb.com/faq/) canonicalized to [https://docs.scylladb.com//faq.html](https://docs.scylladb.com/faq.html) (One has “.html” at the end)

Also seen examples of versions with extra “/” in them.

 

The fix is to :

Ensure the URL used in the rel="canonical" tag for each URL in column A is an exact match of itself (Preferred)

OR

remove rel="canonical" tag from each URL in column A entirely

 

Full Crawl Results and guidance can be found here: https://docs.google.com/spreadsheets/d/1FZUwMI3CXWN4GQgHLJ2jj_2EZHHxIWzg2eWYSAHeLAg/edit#gid=609069639 (tab= Canonicalization & XML Sitemap Update Pt2)

**Comment by dgarcia360** [comment]
Thanks @scynthiadunlop,

I've submitted two pull requests to fix those issues:

1. https://github.com/scylladb/scylla-docs/pull/4008: Removes extra "/" in canonical urls.

2. https://github.com/scylladb/sphinx-scylladb-theme/pull/458: Removes the “/index” in canonical urls.

The changes will be visible when we release the next theme version.
