### ISSUE TITLE
 Working links shouldn't be reported to be broken, even if they use the wrong syntax

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/sphinx-scylladb-theme#446]
Many links reported by the link checker to be broken are not broken, but they use the wrong syntax.
Example:
``
`old format </architecture/sstable/sstable2/sstable-format/>`_ - A working link reported to be broken.
:doc:`old format </architecture/sstable/sstable2/sstable-format/>` - No longer reported when the syntax is fixed.
``
The link checker should only report links that are broken and affect user experience.

**Comment by dgarcia360** [comment]
I think it would be best to use the correct syntax. These links are working right now by chance, but we are not sure they will work with future versions of Sphinx since we are misusing the functionality. For example, if we were to enable the multiversion extension in this project, they would stop working using this syntax.

Please let me know if you would like me to submit a PR to fix the links with the wrong syntax in the scylla-docs project.

**Comment by annastuchlik** [comment]
OK, let's fix the links to make sure they are not broken in the future.
